[package]
name = "zoneminder-aidect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "zm-aidect"
path = "src/main.rs"

[dependencies]
libc = "0.2.126"
memmap2 = "0.5.3"
